// <auto-generated />
namespace TalbatApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rescus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rescus));
        
        string IMigrationMetadata.Id
        {
            get { return "202105220959121_rescus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
